palette = "material_gruvbox"

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](yellow)"

[directory]
truncation_length = 4
style = "bold blue"

[palettes.material_gruvbox]
rosewater = "#f2e5bc"
flamingo = "#ea6962"
pink = "#d3869b"
mauve = "#b16286"
red = "#cc241d"
maroon = "#9d0006"
peach = "#fe8019"
yellow = "#fabd2f"
green = "#98971a"
teal = "#689d6a"
sky = "#458588"
sapphire = "#076678"
blue = "#83a598"
lavender = "#d5c4a1"
text = "#ebdbb2"
subtext1 = "#d5c4a1"
subtext0 = "#bdae93"
overlay2 = "#a89984"
overlay1 = "#928374"
overlay0 = "#7c6f64"
surface2 = "#665c54"
surface1 = "#504945"
surface0 = "#3c3836"
base = "#282828"
mantle = "#1d2021"
crust = "#1b1918"

[palettes.material_gruvbox_light]
rosewater = "#fbf1c7"
flamingo = "#fb4934"
pink = "#d3869b"
mauve = "#b16286"
red = "#cc241d"
maroon = "#9d0006"
peach = "#fe8019"
yellow = "#fabd2f"
green = "#b8bb26"
teal = "#8ec07c"
sky = "#83a598"
sapphire = "#458588"
blue = "#83a598"
lavender = "#d5c4a1"
text = "#3c3836"
subtext1 = "#504945"
subtext0 = "#665c54"
overlay2 = "#7c6f64"
overlay1 = "#928374"
overlay0 = "#a89984"
surface2 = "#bdae93"
surface1 = "#d5c4a1"
surface0 = "#ebdbb2"
base = "#f2e5bc"
mantle = "#fbf1c7"
crust = "#f9f5d7"
